package me.integrate.socialbank;


import android.app.Activity;
import android.graphics.Bitmap;
import android.graphics.BitmapFactory;
import android.support.v4.app.Fragment;
import android.os.Bundle;
import android.support.v7.widget.LinearLayoutManager;
import android.support.v7.widget.RecyclerView;
import android.util.Base64;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Toast;

import com.android.volley.Response;
import com.android.volley.VolleyError;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;


import java.util.ArrayList;
import java.util.List;


public class BoardFragment extends Fragment {


    private static final String URL = "/events";
    private RecyclerView mRecyclerView;
    private RecyclerView.Adapter mAdapter;
    private RecyclerView.LayoutManager mLayoutManager;
    private List<Event> items;

    private String title;
    private String initDate;
    private String place;
    private String finishDate;
    private String individual;
    private String description;
    private String photoEvent;
    private String id;

    PositionRecyclerView mCallback;

    //Comunication with fragment through interface
    public interface PositionRecyclerView{
        public void sendId(String id);
    }

    @Override
    public void onAttach(Activity activity) {
        super.onAttach(activity);

        try {
            mCallback = (PositionRecyclerView) activity;
        } catch (ClassCastException e) {
            e.printStackTrace();
        }
    }

    @Override
    public void onDetach() {
        mCallback = null;
        super.onDetach();
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        // Inflate the layout for this fragment
        View rootView = inflater.inflate(R.layout.fragment_board, container, false);
        mRecyclerView = (RecyclerView) rootView.findViewById(R.id.my_recycler_view);
        mRecyclerView.setHasFixedSize(true);
        mLayoutManager = new LinearLayoutManager(getContext());
        mRecyclerView.setLayoutManager(mLayoutManager);
        inicialBoard(rootView);
        return rootView;
    }

    //Call to the API
    public void getAllEvents(List<Event> items) {

        APICommunicator apiCommunicator = new APICommunicator();
        Response.Listener responseListener = (Response.Listener<CustomRequest.CustomResponse>) response -> {
            JSONArray jsonArray;
            try {
                jsonArray = new JSONArray(response.response);
                for ( int i = 0; i < jsonArray.length(); i++) {
                    JSONObject jsonObject = jsonArray.getJSONObject(i);

                    getInfoEvent(jsonObject);
                    Bitmap decodedByte = getImageFromString(photoEvent);

                    //TODO Vigilar individual
                    items.add(new Event(id, title, initDate, place, finishDate,"No", description, decodedByte));
                }

            } catch (JSONException e) {
                e.printStackTrace();
            }
            //TODO quitar
            Toast.makeText(getActivity().getApplicationContext(), "FUNCIONA!", Toast.LENGTH_LONG).show();
        };
        Toast.makeText(getActivity().getApplicationContext(), "FUNCIOONA!", Toast.LENGTH_LONG).show();
        Response.ErrorListener errorListener = new Response.ErrorListener() {
            @Override
            public void onErrorResponse(VolleyError error) {
                String message;
                int errorCode = error.networkResponse.statusCode;
                if (errorCode == 401)
                    message = "Unauthorized";
                else if(errorCode == 403)
                    message = "Forbidden";
                else if(errorCode == 404)
                    message = "Not Found";
                else
                    message = "Unexpected error";
                Toast.makeText(getActivity().getApplicationContext(), message, Toast.LENGTH_LONG).show();
            }
        };
        apiCommunicator.getRequest(getActivity().getApplicationContext(), URL, responseListener, errorListener,null);
    }

    //Obtain info from the API, create Event and save in the list<Event>
    private void getInfoEvent (JSONObject jsonObject) {

        try {

            id = jsonObject.getString("id");
            title = jsonObject.getString("title");

            initDate = jsonObject.getString("initDate");
            initDate = initDate.substring(8, 10) + "-" + initDate.substring(5, 7) + "-" +
                    initDate.substring(0, 4) + "  " + initDate.substring(11, 19);

            place = jsonObject.getString("place");

            finishDate = jsonObject.getString("endDate");
            finishDate = finishDate.substring(8, 10) + "-" + finishDate.substring(5, 7) + "-" +
                    finishDate.substring(0, 4) + "  " + finishDate.substring(11, 19);

            description = jsonObject.getString("description");

            photoEvent = jsonObject.getString("image");

        } catch (JSONException e) {
            e.printStackTrace();
        }
    }

    //Transform and string base64 to bitmap
    private Bitmap getImageFromString (String image) {
        byte[] decodeString = Base64.decode(image, Base64.DEFAULT);
        Bitmap decodedByte = BitmapFactory.decodeByteArray(decodeString, 0, decodeString.length);
        return decodedByte;

    }


    public void inicialBoard(View v) {

        items = new ArrayList<>();
        //getAllEvents(items);

        //TODO borrar

        String ruben = "iVBORw0KGgoAAAANSUhEUgAABd4AAAQ6CAYAAABaqm9yAAAAAXNSR0ICQMB9xQAAAAlwSFlzAAAXEgAAFiUB9loYUQAAABl0RVh0U29mdHdhcmUATWljcm9zb2Z0IE9mZmljZX/tNXEAAC4ZSURBVHja7djXlt71neVhLmYI9rRTt01uMLi7pwNGoRTB5GSMSUpVpVDKOYGQyEm5VJJKWUJkkXOGdl/Nt1fP0vq/r4znYH7ah8/Bsy9gH34uWLp06QUAAAAAAEDG/52th3+oJ4/9Vz124Ov63cQ764ILLgAAAAAAAP4/Ce8AAAAAABAkvAMAAAAAQFAX3p84/ENtO/ZftVl4BwAAAACAZsI7AAAAAAAE9YX372vbsb/U5gNf1e8m3uEcAAAAAABoILwDAAAAAECQ8A4AAAAAAEG98H7o+9p29C+1eb/wDgAAAAAArYR3AAAAAAAI6sL7lkPf19ajf6lN+7+q64V3AAAAAABoIrwDAAAAAECQ8A4AAAAAAEHCOwAAAAAABAnvAAAAAAAQJLwDAAAAAEBQL7yPf1dbj/xnbRr7sq6fILwDAAAAAEAL4R0AAAAAAIKEdwAAAAAACOrC++Pj39UTR/6zNgrvAAAAAADQTHgHAAAAAIAg4R0AAAAAAIKEdwAAAAAACBLeAQAAAAAgqBfeD35XTxw+G94nCu8AAAAAANCiC++PCe8AAAAAAHDeuvC++eC3teXwD7Vx7AvhHQAAAAAAGgnvAAAAAAAQJLwDAAAAAECQ8A4AAAAAAEHCOwAAAAAABAnvAAAAAAAQJLwDAAAAAECQ8A4AAAAAAEFdeN904Nt6/NAPtWHfF3X9BOEdAAAAAABaCO8AAAAAABAkvAMAAAAAQJDwDgAAAAAAQcI7AAAAAAAECe8AAAAAABAkvAMAAAAAQJDwDgAAAAAAQV1437j/23ps/IdaP/pFXSe8AwAAAABAE+EdAAAAAACChHcAAAAAAAgS3gEAAAAAIEh4BwAAAACAoL7w/k09Nv59rR/9vK6bcLtzAAAAAACggfAOAAAAAABBXXjfsP+b2jz+fa0T3gEAAAAAoJnwDgAAAAAAQb3wPvZNbT74fa3b+3ldd+PtzgEAAAAAgAbCOwAAAAAABAnvAAAAAAAQJLwDAAAAAECQ8A4AAAAAAEHCOwAAAAAABAnvAAAAAAAQ1Bfev65NB7+rtXs/q98K7wAAAAAA0ER4BwAAAACAoB+H9z3COwAAAAAAtDo3vB/4rtbuFt4BAAAAAKCV8A4AAAAAAEHCOwAAAAAABP0ovK8R3gEAAAAAoFkX3tePfV0bD3xXq4V3AAAAAABoJrwDAAAAAECQ8A4AAAAAAEF94f2r2njg21q9+9P67Y23OQcAAAAAABr0wvu+r2rj/rPh/ffCOwAAAAAAtBDeAQAAAAAgSHgHAAAAAIAg4R0AAAAAAILOCe8bzob3a4V3AAAAAABoIrwDAAAAAECQ8A4AAAAAAEHCOwAAAAAABPXC++hXtWHs21q9S3gHAAAAAIBWwjsAAAAAAAT1hfcva8PYN7V61yfCOwAAAAAANBLeAQAAAAAgqAvv60a/rPVj39SqXZ/UNcI7AAAAAAA0Ed4BAAAAACBIeAcAAAAAgCDhHQAAAAAAgoR3AAAAAAAI6oX3vV/W+n3f1Kqdn9Q1NwjvAAAAAADQQngHAAAAAICgLryv3ftFrdv3da3c+XFde8OtzgEAAAAAgAbCOwAAAAAABAnvAAAAAAAQJLwDAAAAAECQ8A4AAAAAAEHCOwAAAAAABAnvAAAAAAAQ1Avve76odaNf18odwjsAAAAAALQS3gEAAAAAIKgL72v2fFFrR7+uFTs+rmuEdwAAAAAAaCK8AwAAAABAkPAOAAAAAABBfeH981o7+lWt2PGR8A4AAAAAAI2EdwAAAAAACBLeAQAAAAAgSHgHAAAAAICgLryv3v15rdn7VS3fLrwDAAAAAEAr4R0AAAAAAIKEdwAAAAAACBLeAQAAAAAgSHgHAAAAAICgvvD+Wa3Z+2Ut3/5hXXPDLc4BAAAAAIAGwjsAAAAAAAQJ7wAAAAAAENSF91W7PqvVe76sZS9/WP/4H8I7AAAAAAC0EN4BAAAAACBIeAcAAAAAgCDhHQAAAAAAgoR3AAAAAAAIEt4BAAAAACBIeAcAAAAAgCDhHQAAAAAAgrrwvnLXp7Vqzxe1VHgHAAAAAIBmwjsAAAAAAAT1wvvOT2vV7i9q6UvCOwAAAAAAtBLeAQAAAAAgSHgHAAAAAIAg4R0AAAAAAIKEdwAAAAAACOrC+4qdn9bK3V/Ukpc+rKuFdwAAAAAAaCK8AwAAAABAkPAOAAAAAABBvfC+45NauevzWvLiB3X1vwvvAAAAAADQQngHAAAAAIAg4R0AAAAAAIKEdwAAAAAACBLeAQAAAAAgSHgHAAAAAICgLrwv3/FJrdj1eS0W3gEAAAAAoJnwDgAAAAAAQcI7AAAAAAAE9cL79k9qxc7Pa/ELwjsAAAAAALQS3gEAAAAAIKgvvH9cK3Z+VotfeL+u/vc/OAcAAAAAABp04X2Z8A4AAAAAAOetC+9Lt39cy3d+ViMvvF9XCe8AAAAAANBEeAcAAAAAgCDhHQAAAAAAgoR3AAAAAAAI6oX3lz+u5Ts+q5Hn36+r/k14BwAAAACAFsI7AAAAAAAECe8AAAAAABAkvAMAAAAAQFAX3pe8/FEt2/FpjTz/nvAOAAAAAACNhHcAAAAAAAgS3gEAAAAAIEh4BwAAAACAIOEdAAAAAACChHcAAAAAAAjqhfeXPqpl2z+tkeeEdwAAAAAAaCW8AwAAAABAkPAOAAAAAABBPwrvi4R3AAAAAABoJrwDAAAAAEDQX4X3T2rRc+/WVf92s3MAAAAAAKCB8A4AAAAAAEHCOwAAAAAABAnvAAAAAAAQ1IX3xS99VEu3f1ILhXcAAAAAAGj2N8P7lcI7AAAAAAA0Ed4BAAAAACBIeAcAAAAAgCDhHQAAAAAAgoR3AAAAAAAI6gvvH9bS7R/XwufeEd4BAAAAAKBRL7y/+GEtffnjWvjsO3XlvwrvAAAAAADQQngHAAAAAICgLryPvPhhLXn541ogvAMAAAAAQDPhHQAAAAAAgoR3AAAAAAAIEt4BAAAAACBIeAcAAAAAgCDhHQAAAAAAgoR3AAAAAAAIEt4BAAAAACCoF95f+KAWv/RRzX/mTF3xrzc5BwAAAAAAGgjvAAAAAAAQJLwDAAAAAECQ8A4AAAAAAEHCOwAAAAAABAnvAAAAAAAQJLwDAAAAAECQ8A4AAAAAAEHCOwAAAAAABAnvAAAAAAAQJLwDAAAAAECQ8A4AAAAAAEHCOwAAAAAABHXhfdELH9TISx/VsPAOAAAAAADNhHcAAAAAAAgS3gEAAAAAIKgX3p//oEZe/KiGnz5TV/wf4R0AAAAAAFoI7wAAAAAAENQX3t+vkRc/rOGn3xbeAQAAAACgkfAOAAAAAABBwjsAAAAAAAQJ7wAAAAAAECS8AwAAAABAkPAOAAAAAABBwjsAAAAAAAQJ7wAAAAAAECS8AwAAAABAUBfeFz7/fi168cMaevrtulx4BwAAAACAJsI7AAAAAAAECe8AAAAAABAkvAMAAAAAQFAvvD/3fi164cMaekp4BwAAAACAVsI7AAAAAAAECe8AAAAAABAkvAMAAAAAQJDwDgAAAAAAQX3h/b1a9MIHNfTUW8I7AAAAAAA0Et4BAAAAACBIeAcAAAAAgCDhHQAAAAAAgoR3AAAAAAAI6sL7gufeq4UvfFCDwjsAAAAAADQT3gEAAAAAIEh4BwAAAACAIOEdAAAAAACChHcAAAAAAAjqhfdn36uFz39Qg0++VZf/i/AOAAAAAAAthHcAAAAAAAgS3gEAAAAAIEh4BwAAAACAIOEdAAAAAACChHcAAAAAAAgS3gEAAAAAIEh4BwAAAACAoC68zxfeAQAAAADgvHXhffjZd2vB8+/X4JNv1uX/MtM5AAAAAADQQHgHAAAAAIAg4R0AAAAAAIKEdwAAAAAACBLeAQAAAAAgSHgHAAAAAIAg4R0AAAAAAIJ64f2Zd2vBc+/X4DbhHQAAAAAAWgnvAAAAAAAQJLwDAAAAAECQ8A4AAAAAAEHCOwAAAAAABAnvAAAAAAAQJLwDAAAAAEBQF96Hnnm35j/3fs3b9mZdJrwDAAAAAEAT4R0AAAAAAIKEdwAAAAAACBLeAQAAAAAgqC+8v1Pzn3uv5m17Q3gHAAAAAIBGwjsAAAAAAAQJ7wAAAAAAECS8AwAAAABAUC+8P/1OzX/2vZq39Y267J+FdwAAAAAAaCG8AwAAAABAkPAOAAAAAABBwjsAAAAAAAQJ7wAAAAAAENSF98Gn36nhZ9+rucI7AAAAAAA0E94BAAAAACBIeAcAAAAAgCDhHQAAAAAAgoR3AAAAAAAIEt4BAAAAACBIeAcAAAAAgCDhHQAAAAAAgoR3AAAAAAAI6gvvZ2r42Xdr7tbX67J/nuEcAAAAAABo0AvvT52p4WeEdwAAAAAAOB/COwAAAAAABAnvAAAAAAAQJLwDAAAAAEBQF97nPXWmhp55t+Zsfb0uFd4BAAAAAKCJ8A4AAAAAAEHCOwAAAAAABAnvAAAAAAAQJLwDAAAAAECQ8A4AAAAAAEHCOwAAAAAABAnvAAAAAAAQJLwDAAAAAECQ8A4AAAAAAEHCOwAAAAAABAnvAAAAAAAQ1AvvT56poaffrTlPCO8AAAAAANCqL7y/XUNPv1NznnhNeAcAAAAAgEY/Cu+zhXcAAAAAAGgmvAMAAAAAQJDwDgAAAAAAQcI7AAAAAAAECe8AAAAAABAkvAMAAAAAQJDwDgAAAAAAQcI7AAAAAAAECe8AAAAAABAkvAMAAAAAQJDwDgAAAAAAQcI7AAAAAAAECe8AAAAAABDUC+/b3q6hp96p2Vteq0v/SXgHAAAAAIAWXXifu+3tGnzqnZq15bX6jfAOAAAAAABNhHcAAAAAAAgS3gEAAAAAIEh4BwAAAACAoL7w/lYNPnWmZm15tX7zT9OdAwAAAAAADYR3AAAAAAAIEt4BAAAAACBIeAcAAAAAgCDhHQAAAAAAgoR3AAAAAAAIEt4BAAAAACBIeAcAAAAAgCDhHQAAAAAAgoR3AAAAAAAI6sL7nG1v1bynztSjjwvvAAAAAADQSngHAAAAAIAg4R0AAAAAAIKEdwAAAAAACBLeAQAAAAAgSHgHAAAAAIAg4R0AAAAAAIKEdwAAAAAACBLeAQAAAAAgqC+8v3k2vJ8W3gEAAAAAoJHwDgAAAAAAQcI7AAAAAAAECe8AAAAAABAkvAMAAAAAQFAX3mdve7PmPnWmHnn8dP1aeAcAAAAAgCbCOwAAAAAABAnvAAAAAAAQ1AvvW9+suU+eqUceO12//p3wDgAAAAAALYR3AAAAAAAIEt4BAAAAACBIeAcAAAAAgCDhHQAAAAAAgoR3AAAAAAAIEt4BAAAAACBIeAcAAAAAgCDhHQAAAAAAgoR3AAAAAAAI6gvvb9TcJ9+uRx57pX79u2nOAQAAAACABl14n7X1jZojvAMAAAAAwHkR3gEAAAAAIEh4BwAAAACAIOEdAAAAAACCeuH9iTdqzra365HNwjsAAAAAALQS3gEAAAAAIEh4BwAAAACAIOEdAAAAAACChHcAAAAAAAgS3gEAAAAAIEh4BwAAAACAIOEdAAAAAACChHcAAAAAAAgS3gEAAAAAIKgL748+8UbN3vZ2PSy8AwAAAABAM+EdAAAAAACChHcAAAAAAAjqC++v1+xtbwnvAAAAAABwHoR3AAAAAAAIEt4BAAAAACCoF963vF6zt75VD296pX59vfAOAAAAAAAthHcAAAAAAAgS3gEAAAAAIEh4BwAAAACAIOEdAAAAAACChHcAAAAAAAgS3gEAAAAAIEh4BwAAAACAoC68P7Ll9Zq19a16aNMr9Q/COwAAAAAANBHeAQAAAAAgSHgHAAAAAIAg4R0AAAAAAIKEdwAAAAAACBLeAQAAAAAgSHgHAAAAAICgXnh//LWa9cSb9dDGU8I7AAAAAAA0Et4BAAAAACBIeAcAAAAAgCDhHQAAAAAAgoR3AAAAAAAIEt4BAAAAACBIeAcAAAAAgKAuvD/8+Gv16BNv1oPCOwAAAAAANBPeAQAAAAAgSHgHAAAAAIAg4R0AAAAAAIKEdwAAAAAACBLeAQAAAAAgSHgHAAAAAIAg4R0AAAAAAIJ64f2x1+rRLcI7AAAAAACcj1543yy8AwAAAADA+RLeAQAAAAAgqC+8v1qPbnmjHtx4sv7h+qnOAQAAAACABsI7AAAAAAAECe8AAAAAABB0Tnh/ZMsb9eeNJ+vvhXcAAAAAAGgivAMAAAAAQJDwDgAAAAAAQcI7AAAAAAAECe8AAAAAABAkvAMAAAAAQJDwDgAAAAAAQcI7AAAAAAAECe8AAAAAABAkvAMAAAAAQFAvvG96tR55/I368wbhHQAAAAAAWgnvAAAAAAAQJLwDAAAAAECQ8A4AAAAAAEFdeH9o06v18ONv1APCOwAAAAAANBPeAQAAAAAgSHgHAAAAAICgvvB+uh5+/PV6YMMJ4R0AAAAAABoJ7wAAAAAAECS8AwAAAABAkPAOAAAAAABBwjsAAAAAAAQJ7wAAAAAAECS8AwAAAABAkPAOAAAAAABBvfC+8XQ9/Njr9cD6E/X31wnvAAAAAADQQngHAAAAAICgH4X3PwnvAAAAAADQrAvvD248XQ899nrdv/5E/Up4BwAAAACAJsI7AAAAAAAECe8AAAAAABAkvAMAAAAAQJDwDgAAAAAAQcI7AAAAAAAECe8AAAAAABD0V+H9tbp//fH61XVTnAMAAAAAAA2EdwAAAAAACBLeAQAAAAAgSHgHAAAAAIAg4R0AAAAAAIJ64X3D6Xpo82t1/zrhHQAAAAAAWgnvAAAAAAAQ1IX3P284XQ8K7wAAAAAAcF6EdwAAAAAACBLeAQAAAAAgSHgHAAAAAIAg4R0AAAAAAIKEdwAAAAAACBLeAQAAAAAgSHgHAAAAAIAg4R0AAAAAAIKEdwAAAAAACBLeAQAAAAAgqC+8v1IPbn617l93THgHAAAAAIBGwjsAAAAAAAQJ7wAAAAAAENSF9wf+J7xverXuX3usfvVb4R0AAAAAAFoI7wAAAAAAECS8AwAAAABAkPAOAAAAAABBwjsAAAAAAAQJ7wAAAAAAECS8AwAAAABAkPAOAAAAAABBwjsAAAAAAAQJ7wAAAAAAECS8AwAAAABAkPAOAAAAAABBwjsAAAAAAASdE97/vOnV+qPwDgAAAAAAzbrw/qcNr9QDm16t+9Yeq18K7wAAAAAA0KQvvJ+qBzadrvvWHq1f/nbAOQAAAAAA0KAX3tefqgc2nq771gjvAAAAAADQ6sfhfbXwDgAAAAAArYR3AAAAAAAIEt4BAAAAACBIeAcAAAAAgCDhHQAAAAAAgoR3AAAAAAAIEt4BAAAAACBIeAcAAAAAgCDhHQAAAAAAgoR3AAAAAAAIEt4BAAAAACCoC+/3rz9Vf9p4uu4V3gEAAAAAoJnwDgAAAAAAQcI7AAAAAAAECe8AAAAAABB0bnjfcDa8Xyu8AwAAAABAi77wfrL+tOGVunf1EeEdAAAAAAAaCe8AAAAAABAkvAMAAAAAQJDwDgAAAAAAQcI7AAAAAAAECe8AAAAAABAkvAMAAAAAQJDwDgAAAAAAQV14/+P6k3X/hlfqHuEdAAAAAACaCe8AAAAAABAkvAMAAAAAQJDwDgAAAAAAQcI7AAAAAAAECe8AAAAAABDUC+/rTtb961+pe1YdqV9eI7wDAAAAAEAL4R0AAAAAAIKEdwAAAAAACBLeAQAAAAAgqC+8n6j7158S3gEAAAAA4DwI7wAAAAAAECS8AwAAAABAkPAOAAAAAABBXXi/b92J+uP6U3X3qiP1C+EdAAAAAACaCO8AAAAAABAkvAMAAAAAQJDwDgAAAAAAQcI7AAAAAAAECe8AAAAAABAkvAMAAAAAQFAvvK89UX9cd6ruXnmkfnGt8A4AAAAAAC2EdwAAAAAACBLeAQAAAAAgSHgHAAAAAIAg4R0AAAAAAIKEdwAAAAAACBLeAQAAAAAgqAvv9649XvetO1V3rTxcv7h2snMAAAAAAKCB8A4AAAAAAEHCOwAAAAAABAnvAAAAAAAQJLwDAAAAAECQ8A4AAAAAAEHCOwAAAAAABAnvAAAAAAAQJLwDAAAAAEBQL7yvOV73rT1Vd604XL+4RngHAAAAAIAWwjsAAAAAAAQJ7wAAAAAAECS8AwAAAABAkPAOAAAAAABBXXi/Z83xunftqbpzxeH6ufAOAAAAAABNhHcAAAAAAAgS3gEAAAAAIEh4BwAAAACAIOEdAAAAAACChHcAAAAAAAjqC+/H6t61J+vOFYeEdwAAAAAAaCS8AwAAAABAkPAOAAAAAABBwjsAAAAAAAT1wvvqY3XvmpN153LhHQAAAAAAWgnvAAAAAAAQJLwDAAAAAECQ8A4AAAAAAEFdeL979bG6Z83JukN4BwAAAACAZsI7AAAAAAAECe8AAAAAABAkvAMAAAAAQJDwDgAAAAAAQcI7AAAAAAAECe8AAAAAABAkvAMAAAAAQJDwDgAAAAAAQcI7AAAAAAAE9YX3o3XPmhN1x/Lx+vk1k5wDAAAAAAANeuF91dG6Z/WJumPZeP38H4V3AAAAAABoIbwDAAAAAECQ8A4AAAAAAEFdeL9r1dG6W3gHAAAAAIDzIrwDAAAAAECQ8A4AAAAAAEHCOwAAAAAABAnvAAAAAAAQJLwDAAAAAECQ8A4AAAAAAEHCOwAAAAAABAnvAAAAAAAQJLwDAAAAAECQ8A4AAAAAAEHCOwAAAAAABAnvAAAAAAAQ1AvvK4/W3atO1B1LhXcAAAAAAGjVhfc7Vx6pu1Ydr9uXHqyfCe8AAAAAANBEeAcAAAAAgCDhHQAAAAAAgoR3AAAAAAAIEt4BAAAAACBIeAcAAAAAgCDhHQAAAAAAgoR3AAAAAAAIEt4BAAAAACBIeAcAAAAAgCDhHQAAAAAAgoR3AAAAAAAIEt4BAAAAACBIeAcAAAAAgKAuvN+x4kjdtfJ43bbkYP3sauEdAAAAAABaCO8AAAAAABAkvAMAAAAAQJDwDgAAAAAAQX3h/XDdtfJY3bbkQP3s6onOAQAAAACABsI7AAAAAAAECe8AAAAAABAkvAMAAAAAQJDwDgAAAAAAQcI7AAAAAAAECe8AAAAAABAkvAMAAAAAQJDwDgAAAAAAQcI7AAAAAAAEdeH99hWH686Vx+rWJQfq74R3AAAAAABoIrwDAAAAAECQ8A4AAAAAAEG98L78cN254ljdulh4BwAAAACAVsI7AAAAAAAECe8AAAAAABAkvAMAAAAAQJDwDgAAAAAAQX3h/VDdueJo3bp4v/AOAAAAAACNhHcAAAAAAAgS3gEAAAAAIEh4BwAAAACAIOEdAAAAAACChHcAAAAAAAg6J7zfseJo3SK8AwAAAABAM+EdAAAAAACChHcAAAAAAAgS3gEAAAAAIKgX3pcdqjuWH61bRvbX31010TkAAAAAANCgF96XCu8AAAAAAHC+hHcAAAAAAAgS3gEAAAAAIEh4BwAAAACAIOEdAAAAAACChHcAAAAAAAgS3gEAAAAAIKgvvI/XHcuP1C0jY8I7AAAAAAA0+n+E9wnOAQAAAACABl14v23peN2+/Ej9YWSs/rfwDgAAAAAATYR3AAAAAAAIEt4BAAAAACBIeAcAAAAAgCDhHQAAAAAAgnrhfcl43b5MeAcAAAAAgPMhvAMAAAAAQJDwDgAAAAAAQcI7AAAAAAAECe8AAAAAABAkvAMAAAAAQJDwDgAAAAAAQcI7AAAAAAAECe8AAAAAABDUhfdbl4zXbcuO1M3COwAAAAAANBPeAQAAAAAgSHgHAAAAAIAg4R0AAAAAAIL6wvvBum3Z4bPhfaJzAAAAAACggfAOAAAAAABBwjsAAAAAAAT9OLwvEt4BAAAAAKCV8A4AAAAAAEHCOwAAAAAABAnvAAAAAAAQJLwDAAAAAECQ8A4AAAAAAEHCOwAAAAAABHXh/ZYlB+vWZYfrpkVj9VPhHQAAAAAAmgjvAAAAAAAQJLwDAAAAAECQ8A4AAAAAAEHCOwAAAAAABAnvAAAAAAAQJLwDAAAAAECQ8A4AAAAAAEG98L74QN269FDdtHBf/fTKCc4BAAAAAIAGwjsAAAAAAAQJ7wAAAAAAECS8AwAAAABAkPAOAAAAAABBwjsAAAAAAAR14f0Piw/ULcI7AAAAAACcF+EdAAAAAACChHcAAAAAAAgS3gEAAAAAIEh4BwAAAACAIOEdAAAAAACChHcAAAAAAAgS3gEAAAAAIEh4BwAAAACAoF54HzlQtyw5VDctEN4BAAAAAKCV8A4AAAAAAEHCOwAAAAAABPWF9/11y5LxumnBqPAOAAAAAACNhHcAAAAAAAjqwvvNI/vrD0vGa6bwDgAAAAAAzYR3AAAAAAAIEt4BAAAAACBIeAcAAAAAgCDhHQAAAAAAgoR3AAAAAAAIEt4BAAAAACBIeAcAAAAAgCDhHQAAAAAAgoR3AAAAAAAIEt4BAAAAACDo3PC+eLxmzh+tn14hvAMAAAAAQAvhHQAAAAAAgoR3AAAAAAAI6sL7TSP76+bF4zVj/mj9RHgHAAAAAIAmwjsAAAAAAAT1hfexunnxwZoxf2/95IobnQMAAAAAAA2EdwAAAAAACBLeAQAAAAAgSHgHAAAAAIAg4R0AAAAAAIKEdwAAAAAACBLeAQAAAAAgSHgHAAAAAIAg4R0AAAAAAIKEdwAAAAAACOqF90VjdfPIwZoxLLwDAAAAAEAr4R0AAAAAAIK68D5z0VjdNHKwpgvvAAAAAADQTHgHAAAAAIAg4R0AAAAAAIKEdwAAAAAACBLeAQAAAAAgSHgHAAAAAICgvwrvB2r68B7hHQAAAAAAGv2N8L5beAcAAAAAgEbCOwAAAAAABAnvAAAAAAAQJLwDAAAAAECQ8A4AAAAAAEHCOwAAAAAABHXhfcbCsZq56EBNG9pdl1wuvAMAAAAAQAvhHQAAAAAAgoR3AAAAAAAIEt4BAAAAACBIeAcAAAAAgCDhHQAAAAAAgoR3AAAAAAAIEt4BAAAAACBIeAcAAAAAgCDhHQAAAAAAgoR3AAAAAAAIEt4BAAAAACCoL7zvq5mL9p8N7793DgAAAAAANBDeAQAAAAAgqAvv08+G96nCOwAAAAAANBPeAQAAAAAgSHgHAAAAAICgXnhfsK9mLtxfUweFdwAAAAAAaCW8AwAAAABAkPAOAAAAAABBwjsAAAAAAAQJ7wAAAAAAECS8AwAAAABAkPAOAAAAAABBwjsAAAAAAAQJ7wAAAAAAECS8AwAAAABAkPAOAAAAAABBXXiftmBfzVi4v6YM7q6LhXcAAAAAAGgivAMAAAAAQJDwDgAAAAAAQX3hfbRmLByrKYO7hHcAAAAAAGjUC+/zhXcAAAAAADhfvfA+PFozFgjvAAAAAABwPoR3AAAAAAAIEt4BAAAAACBIeAcAAAAAgCDhHQAAAAAAgoR3AAAAAAAIEt4BAAAAACBIeAcAAAAAgCDhHQAAAAAAgrrwPnV4tKYvGKsB4R0AAAAAAJoJ7wAAAAAAECS8AwAAAABAkPAOAAAAAABBwjsAAAAAAAQJ7wAAAAAAENQL70OjNX3+WA3M21UXXya8AwAAAABAi77wvremz99XA/N21sWX3eAcAAAAAABoILwDAAAAAECQ8A4AAAAAAEHCOwAAAAAABAnvAAAAAAAQJLwDAAAAAECQ8A4AAAAAAEFdeJ8ytLemCe8AAAAAAHBehHcAAAAAAAgS3gEAAAAAIEh4BwAAAACAIOEdAAAAAACChHcAAAAAAAgS3gEAAAAAIKgX3gf31rThfTUwV3gHAAAAAIBWwjsAAAAAAAQJ7wAAAAAAECS8AwAAAABAUF9431PThkdrYO4O4R0AAAAAABoJ7wAAAAAAECS8AwAAAABAUBfeBwb31NTh0Zo8d0ddJLwDAAAAAEAT4R0AAAAAAIKEdwAAAAAACBLeAQAAAAAgSHgHAAAAAIAg4R0AAAAAAIKEdwAAAAAACBLeAQAAAAAgSHgHAAAAAICgXnift6emDo3W5Dk76qJLhXcAAAAAAGghvAMAAAAAQJDwDgAAAAAAQcI7AAAAAAAECe8AAAAAABDUhffJ8/bUlKHRmiS8AwAAAABAM+EdAAAAAACC+sL77poytLcmzdkuvAMAAAAAQCPhHQAAAAAAgoR3AAAAAAAIEt4BAAAAACBIeAcAAAAAgCDhHQAAAAAAgoR3AAAAAAAIEt4BAAAAACDox+F9tvAOAAAAAACthHcAAAAAAAgS3gEAAAAAIEh4BwAAAACAoC68T5q3uwaG9tbE2dvrQuEdAAAAAACaCO8AAAAAABAkvAMAAAAAQJDwDgAAAAAAQcI7AAAAAAAECe8AAAAAABDUF9531cDQnpo4++W68NL/cA4AAAAAADQQ3gEAAAAAIEh4BwAAAACAIOEdAAAAAACChHcAAAAAAAjqhfe5u2pgcE9NnPVyXfgb4R0AAAAAAFoI7wAAAAAAECS8AwAAAABA0DnhffLgnpogvAMAAAAAQDPhHQAAAAAAgoR3AAAAAAAIEt4BAAAAACBIeAcAAAAAgCDhHQAAAAAAgoR3AAAAAAAIEt4BAAAAACBIeAcAAAAAgCDhHQAAAAAAgvrC+86aPLi7Jsx6SXgHAAAAAIBGwjsAAAAAAAQJ7wAAAAAAENQL73N21uR5u2vCo8I7AAAAAAC06sL7xDk7a9K83XXjoy/V/xLeAQAAAACgifAOAAAAAABBwjsAAAAAAAQJ7wAAAAAAECS8AwAAAABAkPAOAAAAAABBwjsAAAAAAAQJ7wAAAAAAECS8AwAAAABAkPAOAAAAAABBwjsAAAAAAAQJ7wAAAAAAECS8AwAAAABAkPAOAAAAAABBwjsAAAAAAAQJ7wAAAAAAECS8AwAAAABAkPAOAAAAAABBwjsAAAAAAAQJ7wAAAAAAECS8AwAAAABAkPAOAAAAAABBwjsAAAAAAAQJ7wAAAAAAECS8AwAAAABAUF9431WT5u2pGx99WXgHAAAAAIBGwjsAAAAAAAQJ7wAAAAAAECS8AwAAAABAUC+8z91Vkwb31I2zhHcAAAAAAGglvAMAAAAAQJDwDgAAAAAAQcI7AAAAAAAEdeF90txdNXlwT02Y9XJdKLwDAAAAAEAT4R0AAAAAAIL6wvvumjy4tybM2l4X/uYG5wAAAAAAQAPhHQAAAAAAgoR3AAAAAAAIEt4BAAAAACBIeAcAAAAAgCDhHQAAAAAAgoR3AAAAAAAIEt4BAAAAACCoF97n7a7JQ3trwuztdeGlwjsAAAAAALQQ3gEAAAAAIKgvvO+pyUOjNWH2DuEdAAAAAAAaCe8AAAAAABAkvAMAAAAAQJDwDgAAAAAAQcI7AAAAAAAECe8AAAAAABAkvAMAAAAAQJDwDgAAAAAAQeeE94Gh0ZoovAMAAAAAQDPhHQAAAAAAgoR3AAAAAAAI6gvve2tgaF9NnL1TeAcAAAAAgEbCOwAAAAAABAnvAAAAAAAQ9OPwPkd4BwAAAACAVsI7AAAAAAAECe8AAAAAABAkvAMAAAAAQJDwDgAAAAAAQcI7AAAAAAAECe8AAAAAABDUF95Ha2BorCbO2VUXXvp75wAAAAAAQAPhHQAAAAAAgoR3AAAAAAAIEt4BAAAAACBIeAcAAAAAgCDhHQAAAAAAgrrwPnlwtKYMj9WkubvqosuEdwAAAAAAaCG8AwAAAABAkPAOAAAAAABBfeF9X00Z3l+T5u4W3gEAAAAAoJHwDgAAAAAAQcI7AAAAAAAECe8AAAAAABAkvAMAAAAAQJDwDgAAAAAAQcI7AAAAAAAECe8AAAAAABAkvAMAAAAAQJDwDgAAAAAAQcI7AAAAAAAE9YX3sZoyfOBseL/ROQAAAAAA0EB4BwAAAACAoF54HxqrKfMP1KR5wjsAAAAAALQS3gEAAAAAIEh4BwAAAACAoC68DwyN1dT5B2qy8A4AAAAAAM2EdwAAAAAACBLeAQAAAAAgSHgHAAAAAIAg4R0AAAAAAIL+KrwfrMnz9gjvAAAAAADQ6G+E973COwAAAAAANBLeAQAAAAAgSHgHAAAAAIAg4R0AAAAAAIKEdwAAAAAACOqF9+GxmrrgYE0e3FsXXS68AwAAAABAC+EdAAAAAACChHcAAAAAAAgS3gEAAAAAIKgvvO+vqQvGa/LgaF10+QTnAAAAAABAA+EdAAAAAACChHcAAAAAAAgS3gEAAAAAIKgL71OG99e0BeM1MDhaFwvvAAAAAADQRHgHAAAAAIAg4R0AAAAAAIKEdwAAAAAACBLeAQAAAAAgSHgHAAAAAIAg4R0AAAAAAIJ64X3BgZq28FANDO4T3gEAAAAAoJHwDgAAAAAAQcI7AAAAAAAECe8AAAAAABAkvAMAAAAAQJDwDgAAAAAAQcI7AAAAAAAECe8AAAAAABAkvAMAAAAAQJDwDgAAAAAAQX3h/WBNW3i4BgbH6uLLJzoHAAAAAAAaCO8AAAAAABAkvAMAAAAAQFAX3qcuOFjThXcAAAAAADgvvfC+8GBNX3S4BoaEdwAAAAAAaCW8AwAAAABAkPAOAAAAAABBwjsAAAAAAAQJ7wAAAAAAECS8AwAAAABAUF94H6/pi46cDe8TnAMAAAAAAA2EdwAAAAAACBLeAQAAAAAgSHgHAAAAAIAg4R0AAAAAAIKEdwAAAAAACBLeAQAAAAAgSHgHAAAAAICgXnhfNF7TR47UwPBYXXyF8A4AAAAAAC36wvuhmj5ytAaG99fFV0x0DgAAAAAANBDeAQAAAAAgqAvv0xYdqhkjR2uK8A4AAAAAAM2EdwAAAAAACBLeAQAAAAAgSHgHAAAAAIAg4R0AAAAAAIKEdwAAAAAACBLeAQAAAAAgSHgHAAAAAIAg4R0AAAAAAIKEdwAAAAAACOoL74drxsixmjJ8QHgHAAAAAIBGwjsAAAAAAAT1wvvI4Zqx+FhNmS+8AwAAAABAK+EdAAAAAACChHcAAAAAAAgS3gEAAAAAIEh4BwAAAACAIOEdAAAAAACChHcAAAAAAAjqwvv0kSM1c/Hxmjr/YF1yxSTnAAAAAABAA+EdAAAAAACChHcAAAAAAAgS3gEAAAAAIEh4BwAAAACAIOEdAAAAAACChHcAAAAAAAg6N7wvOV5TFxysS64U3gEAAAAAoIXwDgAAAAAAQcI7AAAAAAAE9YX3ozVzyYmaumBceAcAAAAAgEbCOwAAAAAABAnvAAAAAAAQJLwDAAAAAECQ8A4AAAAAAEHCOwAAAAAABAnvAAAAAAAQJLwDAAAAAECQ8A4AAAAAAEHCOwAAAAAABHXhfcbZ8D5NeAcAAAAAgGZ94f1YzVxysqYtOFSXXDnZOQAAAAAA0EB4BwAAAACAoF54X3ysZi49WdMWCu8AAAAAANBKeAcAAAAAgCDhHQAAAAAAgoR3AAAAAAAIEt4BAAAAACBIeAcAAAAAgCDhHQAAAAAAgoR3AAAAAAAI6gvvx2vm0lM1beFh4R0AAAAAABoJ7wAAAAAAECS8AwAAAABAkPAOAAAAAABBwjsAAAAAAAQJ7wAAAAAAENQL70uO18xlp2raosN1yVXCOwAAAAAAtOjC+8wlx+umZadq+qLD9RPhHQAAAAAAmgjvAAAAAAAQJLwDAAAAAEBQX3g/cTa8H6mfXDXgHAAAAAAAaCC8AwAAAABAkPAOAAAAAABBwjsAAAAAAAQJ7wAAAAAAECS8AwAAAABAkPAOAAAAAABBXXgHAAAAAAAy/hsnwZk9qYrHlAAAAABJRU5ErkJggg==";
        Bitmap rub = getImageFromString(ruben);
        items.add(new Event("1","Ferran", "BU", "Aqui", "3-4", "No","bu", rub));
        items.add(new Event("2","Joan", "BU", "Aqui", "3-4", "No","bu", rub));


        mAdapter = new EventAdapter(items, getActivity(), new CustomItemClickListener() {
            @Override
            public void onItemClick(View v, int position) {
                //TODO hacer comunicacion entre fragments
                mCallback.sendId(items.get(position).getId());
            }
        });


        mRecyclerView.setAdapter(mAdapter);
    }

}
